In [12]:
import pandas as pd

In [13]:
df = pd.read_csv('database.csv', low_memory=False, on_bad_lines='skip')
df.head()

,Index,Name,Synon,Campaign/Experimental_Source,Experimental_Conditions,UID,Contributor_ID,Comments,Suspected_Matches,Confirmed_Matches,...,Oven_temp,Publications,Contributor,Date_of_Entry,Num Peaks,5_Highest_Intensity_MZ,Base_Peak,MS,X-Values,Y-Values
0,0,UNK_AHG_LY_ACEDOX_1,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-0,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,198.0,"[73.0, 149.0, 75.0, 267.0, 177.0]",73.0,29 5.0 ; 39 11.0 ; 40 1.0 ; 41 50.0 ; 42 3.0 ;...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 5. 11. 1. 50. 3. 29. 9. 80. 4. ...
1,1,UNK_AHG_LY_ACEDOX_2,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-1,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,175.0,"[149.0, 73.0, 309.0, 191.0, 281.0]",149.0,29 4.0 ; 39 8.0 ; 40 1.0 ; 41 53.0 ; 42 3.0 ; ...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 4. 8. 1. 53. 3. 32. 8. 61. 3. ...
2,2,UNK_AHG_LY_ACEDOX_3,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-2,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,203.0,"[73.0, 149.0, 192.0, 43.0, 117.0]",73.0,29 14.0 ; 31 1.0 ; 39 45.0 ; 40 6.0 ; 41 170.0...,[ 29. 31. 39. 40. 41. 42. 43. 44. 45. ...,[ 14. 1. 45. 6. 170. 14. 694. 32. 139. ...
3,3,UNK_AHG_LY_ACEDOX_4,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-3,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,195.0,"[73.0, 240.0, 225.0, 150.0, 192.0]",73.0,29 11.0 ; 31 1.0 ; 38 1.0 ; 39 36.0 ; 40 5.0 ;...,[ 29. 31. 38. 39. 40. 41. 42. 43. 44. ...,[ 11. 1. 1. 36. 5. 116. 10. 395. 19. ...
4,4,UNK_AHG_LY_ACEDOX_13,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-4,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,162.0,"[149.0, 221.0, 73.0, 107.0, 121.0]",149.0,29 7.0 ; 39 16.0 ; 40 2.0 ; 41 83.0 ; 42 5.0 ;...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 7. 16. 2. 83. 5. 38. 7. 34. 2. ...

In [14]:
df.columns

Index(['Index', 'Name', 'Synon', 'Campaign/Experimental_Source',
       'Experimental_Conditions', 'UID', 'Contributor_ID', 'Comments',
       'Suspected_Matches', 'Confirmed_Matches', 'Predicted_Matches',
       'Compound_Structural_Info', 'Formula', 'MW', 'MW_Prediction',
       'ExactMass', 'VUV_Exact_Mass', 'CAS#', 'Ch3MS-RF_Cnum.p',
       'Ch3MS-RF_OC.p', 'Ch3MS-RF_OSc.p', 'Ch3MS-RF_VP.p', 'Column_Type',
       'Retention_index', 'd_alkane_RTI', 'n_alkane_RTI', 'Instrument',
       'Ionization', 'Injection_method', 'Derivatization_Agent', 'GC_column',
       'Oven_temp', 'Publications', 'Contributor', 'Date_of_Entry',
       'Num Peaks', '5_Highest_Intensity_MZ', 'Base_Peak', 'MS', 'X-Values',
       'Y-Values'],
      dtype='object')

In [15]:
df

,Index,Name,Synon,Campaign/Experimental_Source,Experimental_Conditions,UID,Contributor_ID,Comments,Suspected_Matches,Confirmed_Matches,...,Oven_temp,Publications,Contributor,Date_of_Entry,Num Peaks,5_Highest_Intensity_MZ,Base_Peak,MS,X-Values,Y-Values
0,0,UNK_AHG_LY_ACEDOX_1,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-0,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,198.0,"[73.0, 149.0, 75.0, 267.0, 177.0]",73.0,29 5.0 ; 39 11.0 ; 40 1.0 ; 41 50.0 ; 42 3.0 ;...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 5. 11. 1. 50. 3. 29. 9. 80. 4. ...
1,1,UNK_AHG_LY_ACEDOX_2,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-1,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,175.0,"[149.0, 73.0, 309.0, 191.0, 281.0]",149.0,29 4.0 ; 39 8.0 ; 40 1.0 ; 41 53.0 ; 42 3.0 ; ...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 4. 8. 1. 53. 3. 32. 8. 61. 3. ...
2,2,UNK_AHG_LY_ACEDOX_3,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-2,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,203.0,"[73.0, 149.0, 192.0, 43.0, 117.0]",73.0,29 14.0 ; 31 1.0 ; 39 45.0 ; 40 6.0 ; 41 170.0...,[ 29. 31. 39. 40. 41. 42. 43. 44. 45. ...,[ 14. 1. 45. 6. 170. 14. 694. 32. 139. ...
3,3,UNK_AHG_LY_ACEDOX_4,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-3,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,195.0,"[73.0, 240.0, 225.0, 150.0, 192.0]",73.0,29 11.0 ; 31 1.0 ; 38 1.0 ; 39 36.0 ; 40 5.0 ;...,[ 29. 31. 38. 39. 40. 41. 42. 43. 44. ...,[ 11. 1. 1. 36. 5. 116. 10. 395. 19. ...
4,4,UNK_AHG_LY_ACEDOX_13,NaN,Laboratory Oxidation,ER721GF3 (a-cedrene + O3),LDY-4,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,162.0,"[149.0, 221.0, 73.0, 107.0, 121.0]",149.0,29 7.0 ; 39 16.0 ; 40 2.0 ; 41 83.0 ; 42 5.0 ;...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 7. 16. 2. 83. 5. 38. 7. 34. 2. ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25684,26902,UNK_AHG_HZ_SOAS_749,NaN,SOAS 2013,NaN,LDY-26907,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,154.0,NaN,NaN,29 7.0 ; 31 6.0 ; 39 4.0 ; 40 1.0 ; 41 8.0 ; 4...,NaN,NaN
25685,26903,UNK_AHG_HZ_SOAS_815,NaN,SOAS 2013,NaN,LDY-26908,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,229.0,NaN,NaN,29 7.0 ; 30 2.0 ; 31 3.0 ; 32 14.0 ; 33 1.0 ; ...,NaN,NaN
25686,26904,UNK_AHG_HZ_SOAS_829,NaN,SOAS 2013,NaN,LDY-26909,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,222.0,NaN,NaN,29 7.0 ; 30 1.0 ; 31 1.0 ; 32 1.0 ; 37 1.0 ; 3...,NaN,NaN
25687,26905,"2,3-erythro-dihydroxyglutaric acid iso1",NaN,SOAS 2013,NaN,LDY-26910,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,255.0,NaN,NaN,29 1.0 ; 31 1.0 ; 39 1.0 ; 41 3.0 ; 42 3.0 ; 4...,NaN,NaN
25688,26906,UNK_AHG_HZ_SOAS_49,NaN,SOAS 2013,NaN,LDY-26911,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,295.0,NaN,NaN,29 2.0 ; 30 1.0 ; 32 2.0 ; 33 1.0 ; 34 1.0 ; 3...,NaN,NaN

In [16]:
def col_num_not_na(df: pd.DataFrame, col: str):
    return len(df[~df[col].isna()])
def col_num_unique_values(df: pd.DataFrame, col: str):
    return len(df[col].unique())

In [17]:
print(f'len(df): {len(df)}')
for col in df.columns:
    print(f'---{col}---\n\t Number of entries with "{col}": {col_num_not_na(df, col)}\n\t Number of unique values: {col_num_unique_values(df, col)}')

len(df): 25689
---Index---
	 Number of entries with "Index": 25689
	 Number of unique values: 25689
---Name---
	 Number of entries with "Name": 25689
	 Number of unique values: 25529
---Synon---
	 Number of entries with "Synon": 203
	 Number of unique values: 179
---Campaign/Experimental_Source---
	 Number of entries with "Campaign/Experimental_Source": 25687
	 Number of unique values: 7
---Experimental_Conditions---
	 Number of entries with "Experimental_Conditions": 20205
	 Number of unique values: 22
---UID---
	 Number of entries with "UID": 25689
	 Number of unique values: 25689
---Contributor_ID---
	 Number of entries with "Contributor_ID": 263
	 Number of unique values: 206
---Comments---
	 Number of entries with "Comments": 4757
	 Number of unique values: 1384
---Suspected_Matches---
	 Number of entries with "Suspected_Matches": 4
	 Number of unique values: 5
---Confirmed_Matches---
	 Number of entries with "Confirmed_Matches": 1
	 Number of unique values: 2
---Predicted_Matches---
	 Number of entries with "Predicted_Matches": 22222
	 Number of unique values: 6845
---Compound_Structural_Info---
	 Number of entries with "Compound_Structural_Info": 4221
	 Number of unique values: 46
---Formula---
	 Number of entries with "Formula": 746
	 Number of unique values: 400
---MW---
	 Number of entries with "MW": 683
	 Number of unique values: 230
---MW_Prediction---
	 Number of entries with "MW_Prediction": 22220
	 Number of unique values: 420
---ExactMass---
	 Number of entries with "ExactMass": 518
	 Number of unique values: 369
---VUV_Exact_Mass---
	 Number of entries with "VUV_Exact_Mass": 0
	 Number of unique values: 1
---CAS#---
	 Number of entries with "CAS#": 159
	 Number of unique values: 132
---Ch3MS-RF_Cnum.p---
	 Number of entries with "Ch3MS-RF_Cnum.p": 24998
	 Number of unique values: 23216
---Ch3MS-RF_OC.p---
	 Number of entries with "Ch3MS-RF_OC.p": 24998
	 Number of unique values: 24383
---Ch3MS-RF_OSc.p---
	 Number of entries with "Ch3MS-RF_OSc.p": 24998
	 Number of unique values: 23871
---Ch3MS-RF_VP.p---
	 Number of entries with "Ch3MS-RF_VP.p": 24998
	 Number of unique values: 23861
---Column_Type---
	 Number of entries with "Column_Type": 25663
	 Number of unique values: 3
---Retention_index---
	 Number of entries with "Retention_index": 25494
	 Number of unique values: 3650
---d_alkane_RTI---
	 Number of entries with "d_alkane_RTI": 25479
	 Number of unique values: 2197
---n_alkane_RTI---
	 Number of entries with "n_alkane_RTI": 25515
	 Number of unique values: 2257
---Instrument---
	 Number of entries with "Instrument": 25687
	 Number of unique values: 2
---Ionization---
	 Number of entries with "Ionization": 25687
	 Number of unique values: 4
---Injection_method---
	 Number of entries with "Injection_method": 25687
	 Number of unique values: 2
---Derivatization_Agent---
	 Number of entries with "Derivatization_Agent": 25687
	 Number of unique values: 2
---GC_column---
	 Number of entries with "GC_column": 25687
	 Number of unique values: 2
---Oven_temp---
	 Number of entries with "Oven_temp": 25687
	 Number of unique values: 3
---Publications---
	 Number of entries with "Publications": 20967
	 Number of unique values: 6
---Contributor---
	 Number of entries with "Contributor": 25689
	 Number of unique values: 5
---Date_of_Entry---
	 Number of entries with "Date_of_Entry": 25684
	 Number of unique values: 12
---Num Peaks---
	 Number of entries with "Num Peaks": 25689
	 Number of unique values: 446
---5_Highest_Intensity_MZ---
	 Number of entries with "5_Highest_Intensity_MZ": 22222
	 Number of unique values: 17737
---Base_Peak---
	 Number of entries with "Base_Peak": 22222
	 Number of unique values: 315
---MS---
	 Number of entries with "MS": 25689
	 Number of unique values: 25689
---X-Values---
	 Number of entries with "X-Values": 22222
	 Number of unique values: 22221
---Y-Values---
	 Number of entries with "Y-Values": 22222
	 Number of unique values: 22223

In [25]:
df_mask_name = ~(df['Name'].str.contains('UNK') + df['Name'].str.contains('blob')+ df['Name'].str.contains('N14'))
df_elucidated = df[df_mask_name]
print(df_elucidated.shape)
df_elucidated = df_elucidated.dropna(subset=['Formula'])
print(df_elucidated.shape)
df_elucidated.to_pickle('df_lindsay_test.pkl')
df_elucidated

(581, 41)
(492, 41)

,Index,Name,Synon,Campaign/Experimental_Source,Experimental_Conditions,UID,Contributor_ID,Comments,Suspected_Matches,Confirmed_Matches,...,Oven_temp,Publications,Contributor,Date_of_Entry,Num Peaks,5_Highest_Intensity_MZ,Base_Peak,MS,X-Values,Y-Values
1604,1619,"erythro 2-methyltetrol, 4TMS",NaN,Laboratory Oxidation,ER649GF2 (a-cedrene + NOx + hv),LDY-1619,NaN,Very likely contamination from a prior isopren...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,160.0,"[219.0, 73.0, 117.0, 129.0, 147.0]",219.0,29 2.0 ; 30 1.0 ; 31 2.0 ; 39 3.0 ; 41 7.0 ; 4...,[ 29. 30. 31. 39. 41. 42. 43. 44. 45. ...,[ 2. 1. 2. 3. 7. 1. 15. 9. 61. ...
1968,1988,"threo 2-methyltetrol, 4 TMS",NaN,Laboratory Oxidation,ER649GF2 (a-cedrene + NOx + hv),LDY-1988,NaN,Very likely contamination from a prior isopren...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,127.0,"[73.0, 219.0, 117.0, 129.0, 147.0]",73.0,29 7.0 ; 31 16.0 ; 39 12.0 ; 40 14.0 ; 41 2.0 ...,[ 29. 31. 39. 40. 41. 43. 44. 45. 46. ...,[ 7. 16. 12. 14. 2. 8. 4. 98. 12. ...
3709,3831,"trimethylsilyl 4-((1S,2R)-3,3-dimethyl-2-(3-ox...","beta-nocaryophyllonic acid, TMS",Laboratory Oxidation,ER720GF3 (a-humulene + O3),LDY-3831,NaN,Contaminant from a previous beta-caryophyllene...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,248.0,"[75.0, 73.0, 43.0, 185.0, 137.0]",75.0,29 19.0 ; 30 5.0 ; 31 6.0 ; 34 2.0 ; 36 1.0 ; ...,[ 29. 30. 31. 34. 36. 38. 39. 40. 41. ...,[ 19. 5. 6. 2. 1. 2. 41. 14. 145. ...
5241,5380,"trimethylsilyl 4-((1S,2R)-3,3-dimethyl-2-(3-ox...","beta-nocaryophyllonic acid, TMS",Laboratory Oxidation,ER648GF2 (a-humulene + NOx + hv),LDY-5380,NaN,Contaminant from a previous beta-caryophyllene...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,260.0,"[73.0, 75.0, 43.0, 185.0, 137.0]",73.0,29 14.0 ; 31 7.0 ; 33 3.0 ; 37 1.0 ; 38 5.0 ; ...,[ 29. 31. 33. 37. 38. 39. 40. 41. 42. ...,[ 14. 7. 3. 1. 5. 48. 12. 146. 23. ...
6753,6914,"pinic acid, 2TMS","trimethylsilyl 2,2-dimethyl-3-(2-oxo-2-((trime...",Laboratory Oxidation,alpha-pinene + O3 (high SOA loading),LDY-6914,NaN,"first to elute, larger signal of two isomers; ...",NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Lindsay Yee,11/16/2020,148.0,"[73.0, 129.0, 75.0, 171.0, 157.0]",73.0,29 2.0 ; 39 9.0 ; 40 1.0 ; 41 24.0 ; 42 3.0 ; ...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 2. 9. 1. 24. 3. 19. 9. 77. 5. ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20681,21888,C30 n-alkane,NaN,SOAS 2013,NaN,LDY-21893,C30 n-alkane,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,198.0,"[32.0, 66.0, 50.0, 57.0, 82.0]",32.0,29 70.0 ; 31 34.0 ; 32 999.0 ; 34 88.0 ; 35 32...,[ 29. 31. 32. 34. 35. 39. 41. 43. 45. ...,[ 70. 34. 999. 88. 32. 68. 205. 300. 120. ...
20682,21889,squalene,NaN,SOAS 2013,NaN,LDY-21894,squalene,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,216.0,"[32.0, 73.0, 57.0, 43.0, 41.0]",32.0,31 80.0 ; 32 999.0 ; 34 7.0 ; 35 22.0 ; 36 58....,[ 31. 32. 34. 35. 36. 37. 39. 40. 41. ...,[ 80. 999. 7. 22. 58. 18. 60. 308. 398. ...
20686,21893,"cholesta-3,4-diene",NaN,SOAS 2013,NaN,LDY-21898,"cholesta-3,4-diene",NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,234.0,"[32.0, 73.0, 44.0, 103.0, 59.0]",32.0,29 210.0 ; 30 27.0 ; 31 82.0 ; 32 999.0 ; 33 4...,[ 29. 30. 31. 32. 33. 37. 39. 41. 44. ...,[210. 27. 82. 999. 4. 22. 151. 92. 210. ...
20708,21915,"methyl nitrocatechol isomer, 2 TMS",NaN,SOAS 2013,NaN,LDY-21920,methyl nitrocatechol isomer,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,160.0,"[153.0, 243.0, 143.0, 103.0, 303.0]",153.0,29 1.0 ; 30 2.0 ; 31 2.0 ; 32 28.0 ; 45 10.0 ;...,[ 29. 30. 31. 32. 45. 46. 61. 63. 64. ...,[ 1. 2. 2. 28. 10. 3. 11. 6. 4. ...
25687,26905,"2,3-erythro-dihydroxyglutaric acid iso1",NaN,SOAS 2013,NaN,LDY-26910,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,255.0,NaN,NaN,29 1.0 ; 31 1.0 ; 39 1.0 ; 41 3.0 ; 42 3.0 ; 4...,NaN,NaN

,Index,Name,Synon,Campaign/Experimental_Source,Experimental_Conditions,UID,Contributor_ID,Comments,Suspected_Matches,Confirmed_Matches,...,Oven_temp,Publications,Contributor,Date_of_Entry,Num Peaks,5_Highest_Intensity_MZ,Base_Peak,MS,X-Values,Y-Values
1604,1619,"erythro 2-methyltetrol, 4TMS",NaN,Laboratory Oxidation,ER649GF2 (a-cedrene + NOx + hv),LDY-1619,NaN,Very likely contamination from a prior isopren...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,160.0,"[219.0, 73.0, 117.0, 129.0, 147.0]",219.0,29 2.0 ; 30 1.0 ; 31 2.0 ; 39 3.0 ; 41 7.0 ; 4...,[ 29. 30. 31. 39. 41. 42. 43. 44. 45. ...,[ 2. 1. 2. 3. 7. 1. 15. 9. 61. ...
1968,1988,"threo 2-methyltetrol, 4 TMS",NaN,Laboratory Oxidation,ER649GF2 (a-cedrene + NOx + hv),LDY-1988,NaN,Very likely contamination from a prior isopren...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,127.0,"[73.0, 219.0, 117.0, 129.0, 147.0]",73.0,29 7.0 ; 31 16.0 ; 39 12.0 ; 40 14.0 ; 41 2.0 ...,[ 29. 31. 39. 40. 41. 43. 44. 45. 46. ...,[ 7. 16. 12. 14. 2. 8. 4. 98. 12. ...
3709,3831,"trimethylsilyl 4-((1S,2R)-3,3-dimethyl-2-(3-ox...","beta-nocaryophyllonic acid, TMS",Laboratory Oxidation,ER720GF3 (a-humulene + O3),LDY-3831,NaN,Contaminant from a previous beta-caryophyllene...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,248.0,"[75.0, 73.0, 43.0, 185.0, 137.0]",75.0,29 19.0 ; 30 5.0 ; 31 6.0 ; 34 2.0 ; 36 1.0 ; ...,[ 29. 30. 31. 34. 36. 38. 39. 40. 41. ...,[ 19. 5. 6. 2. 1. 2. 41. 14. 145. ...
5241,5380,"trimethylsilyl 4-((1S,2R)-3,3-dimethyl-2-(3-ox...","beta-nocaryophyllonic acid, TMS",Laboratory Oxidation,ER648GF2 (a-humulene + NOx + hv),LDY-5380,NaN,Contaminant from a previous beta-caryophyllene...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,260.0,"[73.0, 75.0, 43.0, 185.0, 137.0]",73.0,29 14.0 ; 31 7.0 ; 33 3.0 ; 37 1.0 ; 38 5.0 ; ...,[ 29. 31. 33. 37. 38. 39. 40. 41. 42. ...,[ 14. 7. 3. 1. 5. 48. 12. 146. 23. ...
6753,6914,"pinic acid, 2TMS","trimethylsilyl 2,2-dimethyl-3-(2-oxo-2-((trime...",Laboratory Oxidation,alpha-pinene + O3 (high SOA loading),LDY-6914,NaN,"first to elute, larger signal of two isomers; ...",NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Lindsay Yee,11/16/2020,148.0,"[73.0, 129.0, 75.0, 171.0, 157.0]",73.0,29 2.0 ; 39 9.0 ; 40 1.0 ; 41 24.0 ; 42 3.0 ; ...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 2. 9. 1. 24. 3. 19. 9. 77. 5. ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20682,21889,squalene,NaN,SOAS 2013,NaN,LDY-21894,squalene,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,216.0,"[32.0, 73.0, 57.0, 43.0, 41.0]",32.0,31 80.0 ; 32 999.0 ; 34 7.0 ; 35 22.0 ; 36 58....,[ 31. 32. 34. 35. 36. 37. 39. 40. 41. ...,[ 80. 999. 7. 22. 58. 18. 60. 308. 398. ...
20686,21893,"cholesta-3,4-diene",NaN,SOAS 2013,NaN,LDY-21898,"cholesta-3,4-diene",NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,234.0,"[32.0, 73.0, 44.0, 103.0, 59.0]",32.0,29 210.0 ; 30 27.0 ; 31 82.0 ; 32 999.0 ; 33 4...,[ 29. 30. 31. 32. 33. 37. 39. 41. 44. ...,[210. 27. 82. 999. 4. 22. 151. 92. 210. ...
20705,21912,isomer of 10-hydroxypinonic acid?,NaN,SOAS 2013,NaN,LDY-21917,isomer of 10-hydroxypinonic acid?,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,196.0,"[73.0, 143.0, 75.0, 83.0, 171.0]",73.0,29 5.0 ; 30 1.0 ; 31 2.0 ; 32 1.0 ; 33 1.0 ; 3...,[ 29. 30. 31. 32. 33. 34. 35. 36. 37. ...,[ 5. 1. 2. 1. 1. 1. 1. 1. 1. ...
20708,21915,"methyl nitrocatechol isomer, 2 TMS",NaN,SOAS 2013,NaN,LDY-21920,methyl nitrocatechol isomer,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,160.0,"[153.0, 243.0, 143.0, 103.0, 303.0]",153.0,29 1.0 ; 30 2.0 ; 31 2.0 ; 32 28.0 ; 45 10.0 ;...,[ 29. 30. 31. 32. 45. 46. 61. 63. 64. ...,[ 1. 2. 2. 28. 10. 3. 11. 6. 4. ...
25687,26905,"2,3-erythro-dihydroxyglutaric acid iso1",NaN,SOAS 2013,NaN,LDY-26910,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,255.0,NaN,NaN,29 1.0 ; 31 1.0 ; 39 1.0 ; 41 3.0 ; 42 3.0 ; 4...,NaN,NaN

In [19]:
print(len(df[~(df['Name'].str.contains('UNK') + df['Name'].str.contains('blob')+ df['Name'].str.contains('N14')) ]['Name'].values))
df[~(df['Name'].str.contains('UNK') + df['Name'].str.contains('blob')+ df['Name'].str.contains('N14')) ]

581

,Index,Name,Synon,Campaign/Experimental_Source,Experimental_Conditions,UID,Contributor_ID,Comments,Suspected_Matches,Confirmed_Matches,...,Oven_temp,Publications,Contributor,Date_of_Entry,Num Peaks,5_Highest_Intensity_MZ,Base_Peak,MS,X-Values,Y-Values
1604,1619,"erythro 2-methyltetrol, 4TMS",NaN,Laboratory Oxidation,ER649GF2 (a-cedrene + NOx + hv),LDY-1619,NaN,Very likely contamination from a prior isopren...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,160.0,"[219.0, 73.0, 117.0, 129.0, 147.0]",219.0,29 2.0 ; 30 1.0 ; 31 2.0 ; 39 3.0 ; 41 7.0 ; 4...,[ 29. 30. 31. 39. 41. 42. 43. 44. 45. ...,[ 2. 1. 2. 3. 7. 1. 15. 9. 61. ...
1968,1988,"threo 2-methyltetrol, 4 TMS",NaN,Laboratory Oxidation,ER649GF2 (a-cedrene + NOx + hv),LDY-1988,NaN,Very likely contamination from a prior isopren...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,127.0,"[73.0, 219.0, 117.0, 129.0, 147.0]",73.0,29 7.0 ; 31 16.0 ; 39 12.0 ; 40 14.0 ; 41 2.0 ...,[ 29. 31. 39. 40. 41. 43. 44. 45. 46. ...,[ 7. 16. 12. 14. 2. 8. 4. 98. 12. ...
3709,3831,"trimethylsilyl 4-((1S,2R)-3,3-dimethyl-2-(3-ox...","beta-nocaryophyllonic acid, TMS",Laboratory Oxidation,ER720GF3 (a-humulene + O3),LDY-3831,NaN,Contaminant from a previous beta-caryophyllene...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,248.0,"[75.0, 73.0, 43.0, 185.0, 137.0]",75.0,29 19.0 ; 30 5.0 ; 31 6.0 ; 34 2.0 ; 36 1.0 ; ...,[ 29. 30. 31. 34. 36. 38. 39. 40. 41. ...,[ 19. 5. 6. 2. 1. 2. 41. 14. 145. ...
5241,5380,"trimethylsilyl 4-((1S,2R)-3,3-dimethyl-2-(3-ox...","beta-nocaryophyllonic acid, TMS",Laboratory Oxidation,ER648GF2 (a-humulene + NOx + hv),LDY-5380,NaN,Contaminant from a previous beta-caryophyllene...,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Yee, L. D., Isaacman-Vanwertz, G., Wernis, R. ...",Lindsay Yee,11/16/2020,260.0,"[73.0, 75.0, 43.0, 185.0, 137.0]",73.0,29 14.0 ; 31 7.0 ; 33 3.0 ; 37 1.0 ; 38 5.0 ; ...,[ 29. 31. 33. 37. 38. 39. 40. 41. 42. ...,[ 14. 7. 3. 1. 5. 48. 12. 146. 23. ...
6753,6914,"pinic acid, 2TMS","trimethylsilyl 2,2-dimethyl-3-(2-oxo-2-((trime...",Laboratory Oxidation,alpha-pinene + O3 (high SOA loading),LDY-6914,NaN,"first to elute, larger signal of two isomers; ...",NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Lindsay Yee,11/16/2020,148.0,"[73.0, 129.0, 75.0, 171.0, 157.0]",73.0,29 2.0 ; 39 9.0 ; 40 1.0 ; 41 24.0 ; 42 3.0 ; ...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 2. 9. 1. 24. 3. 19. 9. 77. 5. ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20682,21889,squalene,NaN,SOAS 2013,NaN,LDY-21894,squalene,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,216.0,"[32.0, 73.0, 57.0, 43.0, 41.0]",32.0,31 80.0 ; 32 999.0 ; 34 7.0 ; 35 22.0 ; 36 58....,[ 31. 32. 34. 35. 36. 37. 39. 40. 41. ...,[ 80. 999. 7. 22. 58. 18. 60. 308. 398. ...
20686,21893,"cholesta-3,4-diene",NaN,SOAS 2013,NaN,LDY-21898,"cholesta-3,4-diene",NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,234.0,"[32.0, 73.0, 44.0, 103.0, 59.0]",32.0,29 210.0 ; 30 27.0 ; 31 82.0 ; 32 999.0 ; 33 4...,[ 29. 30. 31. 32. 33. 37. 39. 41. 44. ...,[210. 27. 82. 999. 4. 22. 151. 92. 210. ...
20705,21912,isomer of 10-hydroxypinonic acid?,NaN,SOAS 2013,NaN,LDY-21917,isomer of 10-hydroxypinonic acid?,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,196.0,"[73.0, 143.0, 75.0, 83.0, 171.0]",73.0,29 5.0 ; 30 1.0 ; 31 2.0 ; 32 1.0 ; 33 1.0 ; 3...,[ 29. 30. 31. 32. 33. 34. 35. 36. 37. ...,[ 5. 1. 2. 1. 1. 1. 1. 1. 1. ...
20708,21915,"methyl nitrocatechol isomer, 2 TMS",NaN,SOAS 2013,NaN,LDY-21920,methyl nitrocatechol isomer,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,160.0,"[153.0, 243.0, 143.0, 103.0, 303.0]",153.0,29 1.0 ; 30 2.0 ; 31 2.0 ; 32 28.0 ; 45 10.0 ;...,[ 29. 30. 31. 32. 45. 46. 61. 63. 64. ...,[ 1. 2. 2. 28. 10. 3. 11. 6. 4. ...
25687,26905,"2,3-erythro-dihydroxyglutaric acid iso1",NaN,SOAS 2013,NaN,LDY-26910,NaN,NaN,NaN,NaN,...,40 C to 320 C at 3.5 C/min,"Zhang, H., Yee, L. D., Lee, B. H., Curtis, M. ...",Haofei Zhang,4/27/2021,255.0,NaN,NaN,29 1.0 ; 31 1.0 ; 39 1.0 ; 41 3.0 ; 42 3.0 ; 4...,NaN,NaN

In [20]:
predicted_matches_not_na = df[~df['Predicted_Matches'].isna()]
predicted_matches_not_list_empty = predicted_matches_not_na['Predicted_Matches'].apply(lambda x: x if '[]' not in x and 'nan' not in x else None)
predicted_matches_not_list_empty = predicted_matches_not_list_empty.apply(lambda x: not isinstance(x, type(None)))
predicted_matches_not_na[predicted_matches_not_list_empty]['Predicted_Matches']

0                    ['LDY-1094', 'LDY-14785', 'LDY-2330']
1                      ['LDY-1092', 'LDY-14775', 'LDY-15']
2                                ['LDY-1090', 'LDY-14788']
3                                ['LDY-14784', 'LDY-1100']
4                                   ['LDY-12', 'LDY-1106']
                               ...
22202                                        ['LDY-14616']
22206                ['LDY-7531', 'LDY-21125', 'LDY-6928']
22207                                        ['LDY-23006']
22209    ['LDY-23423', 'LDY-14720', 'LDY-14706', 'LDY-9...
22213                                        ['LDY-22003']
Name: Predicted_Matches, Length: 6308, dtype: object

In [21]:
els=[]
for el in df['Predicted_Matches'].unique():
    els.append(type(el))
print(set(els))

{<class 'float'>, <class 'str'>}

In [22]:
predicted_matches_not_na.tail(5)['']

KeyError: ''

In [ ]:
formula_df = df[~df['Formula'].isna()][['Name', 'Formula', 'CAS#', 'MW', 'Compound_Structural_Info', 'UID', 'MS', 'X-Values', 'Y-Values']]
formula_df[~formula_df['Compound_Structural_Info'].isna()]

,Name,Formula,CAS#,MW,Compound_Structural_Info,UID,MS,X-Values,Y-Values
6754,"pinonic acid, TMS",C13H24O3Si,NaN,256.420,1 of 2 isomers,LDY-6915,29 2.0 ; 39 16.0 ; 40 2.0 ; 41 40.0 ; 42 5.0 ;...,[ 29. 39. 40. 41. 42. 43. 44. 45. 46. ...,[ 2. 16. 2. 40. 5. 125. 10. 61. 4. ...
6756,UNK_AHG_LY_APINOX_4,C11H20O4Si,NaN,244.360,Underivatized structure propose to contain one...,LDY-6917,29 2.0 ; 31 2.0 ; 38 1.0 ; 39 26.0 ; 40 5.0 ; ...,[ 29. 31. 38. 39. 40. 41. 42. 43. 44. ...,[ 2. 2. 1. 26. 5. 57. 12. 82. 13. ...
6763,pinonaldehyde isomer 2,C10H16O2,NaN,168.240,1 of 2 isomers,LDY-6924,29 13.0 ; 31 1.0 ; 37 2.0 ; 38 6.0 ; 39 79.0 ;...,[ 29. 31. 37. 38. 39. 40. 41. 42. 43. ...,[ 13. 1. 2. 6. 79. 12. 218. 24. 452. ...
6767,"pinonic acid, TMS isomer",C13H24O3Si,NaN,256.420,1 of 2 isomers,LDY-6928,29 10.0 ; 30 1.0 ; 31 3.0 ; 37 1.0 ; 38 2.0 ; ...,[ 29. 30. 31. 37. 38. 39. 40. 41. 42. ...,[ 10. 1. 3. 1. 2. 36. 5. 117. 19. ...
6771,"Silanol, trimethyl-, phosphate (3:1)",C9H27O4PSi3,10497-05-9,314.000,3 derivatized OH groups,LDY-6932,29 1.0 ; 31 1.0 ; 42 1.0 ; 43 10.0 ; 44 8.0 ; ...,[ 29. 31. 42. 43. 44. 45. 46. 47. 49. ...,[ 1. 1. 1. 10. 8. 80. 4. 10. 1. ...
...,...,...,...,...,...,...,...,...,...
20004,UNK_AHG_HZ_SOAS_97,C7H9NO6,NaN,NaN,"Contains N, OH>=2; maybe C7H7NO4(OH)2?",LDY-21212,31 2.0 ; 40 1.0 ; 41 6.0 ; 42 4.0 ; 43 244.0 ;...,[ 31. 40. 41. 42. 43. 44. 45. 46. 47. ...,[ 2. 1. 6. 4. 244. 16. 90. 2. 27. ...
20010,UNK_AHG_HZ_SOAS_103,C8H11NO6,NaN,NaN,"Contains N, OH>=2; maybe C8H9NO4(OH)2",LDY-21218,29 3.0 ; 30 1.0 ; 31 2.0 ; 32 1.0 ; 33 1.0 ; 3...,[ 29. 30. 31. 32. 33. 39. 40. 41. 42. ...,[ 3. 1. 2. 1. 1. 8. 3. 29. 7. ...
20019,UNK_AHG_HZ_SOAS_112,C6H7NO6,NaN,NaN,OH >=2; maybe C6H4NO3(OH)3,LDY-21227,29 40.0 ; 30 1.0 ; 31 2.0 ; 32 4.0 ; 33 1.0 ; ...,[ 29. 30. 31. 32. 33. 34. 35. 36. 37. ...,[ 40. 1. 2. 4. 1. 2. 2. 2. 3. ...
20024,UNK_AHG_HZ_SOAS_117,C14H30O4Si2,NaN,318.417,2 OH groups,LDY-21232,29 9.0 ; 30 1.0 ; 31 2.0 ; 36 1.0 ; 37 1.0 ; 3...,[ 29. 30. 31. 36. 37. 38. 39. 40. 41. ...,[ 9. 1. 2. 1. 1. 2. 16. 4. 71. ...
20071,UNK_AHG_HZ_SOAS_164,C14H30O4Si2,NaN,318.417,2 OH groups,LDY-21279,29 6.0 ; 31 2.0 ; 32 1.0 ; 34 2.0 ; 38 2.0 ; 3...,[ 29. 31. 32. 34. 38. 39. 40. 41. 42. ...,[ 6. 2. 1. 2. 2. 29. 7. 104. 15. ...